# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: YmEwY2I4MDhiYjI2NWYyYzJlN2NkMWM0NThiMDUwYTkyOTdiOTU4MzJmMTQ2MTYwNGU1NzlkNGUzNzdhMjUwMDRjNDFiMjIwMWUwZGVkNGJmMzk3NTgxN2Q2ZmI5ZGY5MzMyNzZkZTRmZGI3MDlmYzJlYzJiZWJjNzVmNWQ2MTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
